services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"
